memes:
  prefix: asteurer-com-memes
  database:
    secrets:
    - name: postgres-password
      path: vaults/asteurer.com_apps/items/memes_database
      key: password
    - name: postgres-user
      path: vaults/asteurer.com_apps/items/memes_database
      key: username
  client:
    image: ghcr.io/asteurer/asteurer.com-memes-client
    secrets:
      - name: aws-access-key
        path: vaults/asteurer.com_apps/items/s3_meme_manager
        key: access_key
      - name: aws-secret-key
        path: vaults/asteurer.com_apps/items/s3_meme_manager
        key: secret_access_key
      - name: aws-s3-region
        path: vaults/asteurer.com_apps/items/s3_meme_manager
        key: s3_region
      - name: aws-s3-bucket
        path: vaults/asteurer.com_apps/items/s3_meme_manager
        key: s3_bucket
      - name: auth-user
        path: vaults/asteurer.com_apps/items/auth_memes_client
        key: username
      - name: auth-password
        path: vaults/asteurer.com_apps/items/auth_memes_client
        key: password